name: penaislam_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  intl: ^0.20.2
  file_picker: ^8.1.2
  equatable: ^2.0.5
  stacked: ^3.4.2
  stacked_services: ^1.6.0
  logger: ^1.4.0
  url_launcher: ^6.3.0
  sentry_flutter: ^8.12.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  sentry_dart_plugin: ^2.4.1
  cupertino_icons: ^1.0.6
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/steve.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/steve.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/steve.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/steve.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/steve.png"

sentry:
  project: my_app-2f4441
  org: o-46
  auth_token: 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
  upload_source_maps: true
  ignore_missing: true
